### PR TITLE
Improve dls with more switches and list options.

### PR DESCRIPTION
**Pull request by calancha**
Allow list ordering by file size (-S, --sizeorder).
Support on listing in human readable format (-h, --human-readable).
Support reverse list ordering (-r, --reverse).

### CODE REVIEW

**Comment by calancha** [comment]
Thank you. I will close this pull and open a new one with your fix.

**Comment by pigay** [comment]
You could have added a new commit to this branch instead of opening a new one?

Cheers

**Comment by calancha** [comment]
Sorry, I am still very new in github: i dont fully understand the PR process.

**Comment by pigay** [comment]
It was also a question. I'm fairly new too ;)

Thanks anyway ;)

**Comment by calancha** [comment]
Ok. Github is fun, let's enjoy!

**Comment by atsareg** [comment]
A word about GitHub PRs. When you make a PR you do it starting from a branch, let say A, in your forked repository. Until the PR is merged in you can add new commits to your branch A, all those commits will be considered to be part of the same PR. This way you can react to the review comments on your PR just adding new commits without remaking the PR itself.

**Comment by calancha** [comment]
Thank you so much Andrei. Very useful.

**Pull request closed without merging**
