### PR TITLE
Improve dls with more switches and list options

### PR DESCRIPTION
**Pull request by calancha**
Allow list ordering by file size (-S, --sizeorder).
Support on listing in human readable format (-h, --human-readable).
Support reverse list ordering (-r, --reverse).

### CODE REVIEW

**Comment by pigay** [comment]
Thanks for the contribution.

**Comment by atsareg** [comment]
Can I ask you to see together how the common stuff in COMDIRAC and FileCatalogClientCLI can be placed as a set of utilities in DataManagementSystem/Utilities/CLIUtilities.py, for example, to avoid code duplication.

**Comment by calancha** [comment]
I would like very much: i hate code duplication. But i have internation workshop next week so i would prefer start with this project after that event.

**Comment by pigay** [comment]
@calancha: We could work on this together if you want. Feel free to contact me at pierre.gay@NOSPAM@u-bordeaux.fr when you are ready.

**Comment by calancha** [comment]
Sure, i count with you. I sent you e-mail with i finish my incoming dutie.

**Pull request merged**
